### ISSUE TITLE
Add link styles to content wall drop-down

### ISSUE THREAD

**Issue by alexjohnston266** [comicrelief/campaign#1141]
In content wall nodes, the only options on the link drop-down menu are the button styles. Can we please add the link styles to this list as well?

![link dropdown](https://user-images.githubusercontent.com/29603446/29127973-71e455f6-7d1a-11e7-9351-ad6d5871a190.png)

**Comment by gusliedke** [comment]
Change label "Button colour" to "CTA style". And add btn and links styles to the dropdown selector.

**Comment by Heleen-cr** [comment]
### Test notes:

- go to: https://pr-1267-dmzgzfq-tx3mbsqmxtu74.eu.platform.sh
- log in
- edit a Teaser block in a Content wall.
- the button fields should now have 'CTA' instead of 'button' in their labels
- the CTA style drop down should have all the campaign button styles and links (not inline links though).
- The styling for the button/style should come through on the page.

**Comment by k-pammi** [comment]
@Heleen-cr : Passed QA
