### ISSUE TITLE
Cross-site Email Sign Up 

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1424]
As a user who wants to receive updates from Comic Relief via email, I need an easy way to register onto a mailing list on their websites.

**Requirement:**
Collect email address
Ensure user understands what they're signing up for
Access the sign up from anywhere on the website

**Compliance bit:** 
Link to privacy policy: https://www.comicrelief.com/privacy-notice 
Have copy _"If you are under 18, please make sure you’ve got your parents’ permission before providing us with any personal details."_

**Comment by LaBustaffa** [comment]
Prototype: https://marvelapp.com/925hd8h/screen/44135706
Visuals: https://comicrelief.box.com/s/y9u025lk9mtqreeviep4yrllx1265tou

The spacing of elements is indicative of proportions and doesn't need to be pixel perfect.

**Comment by CarolineRennie** [comment]
Sport Relief
![image](https://user-images.githubusercontent.com/23260070/41342592-87bff764-6ef4-11e8-8684-486a970e3fe0.png)

Comic Relief
![image](https://user-images.githubusercontent.com/23260070/41342633-a0918b2c-6ef4-11e8-8100-9831021441a3.png)

**Comment by Heleen-cr** [comment]
@LaBustaffa Could you have a look at the ESU on CR and see if you want something tweaked?
I've made it work for the Email signup link in the new turbofooter too, so if you could check that too. (the turbofooter obviously looks a bit shite with the 3 links I gave it, please ignore that)

https://562-new-email-signup-75njxui-3g6y4v7pqt6nk.eu.platform.sh/

**Comment by Heleen-cr** [comment]
@LaBustaffa 
- I placed the popup right underneath the header now, because otherwise there would be too much space from the top if the popup is opened from the footer.
- scrolling is fixed
- the spacing inside the popup is fixed to 30px in between items.

preview environment for CR: https://562-new-email-signup-75njxui-3g6y4v7pqt6nk.eu.platform.sh/
Need to push the latest updates for SR to the preview environment.. this will follow soon.

@k-pammi Could you test the new ESU on CR?

**Comment by LaBustaffa** [comment]
Looks good!

**Comment by Heleen-cr** [comment]
@k-pammi 
CR: https://562-new-email-signup-75njxui-3g6y4v7pqt6nk.eu.platform.sh/
SR: http://pr-430-zdpjs6i-mw3yu47main2e.eu.platform.sh/

**Comment by k-pammi** [comment]
Verified
1. ESU on CR, when the cookie message is open on the site and clicked on ESU, the ESU block is overlapped on header cutting off the header
![image](https://user-images.githubusercontent.com/16117926/47216423-d2375280-d39c-11e8-85a1-844e622650a6.png)

2. ESU email input field looks too long on both CR and SR
![image](https://user-images.githubusercontent.com/16117926/47218070-766fc800-d3a2-11e8-98eb-1fa7125c59a5.png)

3. On IE11, email input field and subscribe button on both CR and SR ESU is aligned to the right instead of left
![image](https://user-images.githubusercontent.com/16117926/47217421-31e32d00-d3a0-11e8-930c-f50bb6b828f1.png)

4. On IE11 When I don't enter an email and click on subscribe button, the subscribe button shows where it's expected but the input field is aligned to the text 'Stay In the Know'
![image](https://user-images.githubusercontent.com/16117926/47219062-a5d40400-d3a5-11e8-802c-a27ffe611c4b.png)

5. SR ESU on mobile devices, when the cookie message is kept open and clicked on ESU, ESU block is static but the homepage and the cookie message scrolls when the page I scroll it, when the page is scrolled the cookie message scrolls over the ESU and when not scrolled it covers `Stay in the know!` text
(cookie message covering the text happens on CR esu too)

**Comment by Heleen-cr** [comment]
@k-pammi managed to fix sportrelief there. http://429-new-esu-w7zahva-mw3yu47main2e.eu.platform.sh/
It shouldn't scroll anymore.
Will rebuild CR too.

**Comment by Heleen-cr** [comment]
@k-pammi and here's CR: http://562-new-email-signup-75njxui-3g6y4v7pqt6nk.eu.platform.sh/
Could you test again when you get the chance?

**Comment by k-pammi** [comment]
Discussed the issues with @Heleen-cr 
Noting down the issues here just so I won't forget later
1. Issue 1 still exists - solution: to move the ESU block down the header menu on desktop and mobiles just like how search works
2. Fix the space issue in the error message (move the text close to the icon)
3. Scrolling issue

**Comment by Heleen-cr** [comment]
@k-pammi Should all be fixed now.
