### ISSUE TITLE
Cookie banner updates for GDPR

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1443]
Investigate how we handle cookie banner and cookie storage across all our site.

**Comment by phiral** [comment]
As part of GDPR and EU Data Protection law we must tell our users if we set cookies, and clearly explain what the cookies do and why. We must also get the user’s consent which must be actively and clearly given.

**Cookie Banner Proposal**

Implement standardised Cookie banner across all Comic Relief websites and applications:

1. Overlay to take over the page when a user land on a page
2. When selecting “I Accept” the user should  be opted into all options
3. When selection Settings/Control present user options popup

See proposed user flow below:

![cookie-banner-flow_26092018](https://user-images.githubusercontent.com/6840397/46078933-86bec980-c18d-11e8-9948-b5234a2bb064.png)

This solution should allow retrievable indicator to check what level of opt-in the user has opted into and where ever possible we are required to keep a log of this selection. 

For us to send this information into our analytics platform please make available and retrievable the following information when a selection has been made  i.e. local storage

Also we could look to manage some of this via Google Tag Manager (GTM). Please give me a shout to chat more.

**Further reading:** 

The following requirements in the General Data Protection Regulation (GDPR) and the ePrivacy Directive (ePR) has to be implemented:

- Prior consent on other than strictly necessary cookies (ePR)
- Prior consent on personal data (GDPR)
- Personal data is transmitted to 'adequate countries' only (GDPR)

**Please also make sure to:**

- Inform your visitors in plain language about the purpose of your cookies and trackers before setting other than strictly necessary cookies (ePR)
- Provide options for the visitor to change or withdraw a consent (GDPR/ePR)
- Have a mechanism in place to log and prove consents (GDPR)
- Map and document data streams performed by third parties (GDPR)
- Configure your consent method to use explicit/active consent when processing sensitive personal data on your website (GDPR)
- Provide the identity and contact details of the data controller in your company (GDPR)
- Disclose that the visitor is entitled to access, correct, delete and limit processing of personal data (GDPR)
- Disclose that the visitor is entitled to receive personal data so that they can be used by another processor (GDPR)
- Disclose that the visitor has the right to lodge a complaint with a supervisory authority (GDPR)
- Inform about the occurrence of automatic decisions, including profiling (GDPR)

**Comment by phiral** [comment]
@here please find below our audited cookie list, this has now been categorised as follows:

- Necessary Cookies
- Performance Cookies
- Advertising Cookies

[CR_Cookie_Audit_052017.xlsx](https://github.com/comicrelief/campaign/files/2535261/CR_Cookie_Audit_052017.xlsx)

**Comment by AndyEPhipps** [comment]
@phiral : gonna suggest we have a short kick-off meeting about this? I feel like some of this stuff is better explained in person

**Comment by AndyEPhipps** [comment]
We ended up doing the work straight into CR.com, but I'm gonna move this just to Campaign now so both CR and SR can use the same code.
